fix(github): upload assets to github do not failed if the file not found on github

diff --git a/lib/bash/github b/lib/bash/github
--- a/lib/bash/github
+++ b/lib/bash/github
@@ -46,29 +46,43 @@ _github-upload-one() {
     exit 1
   fi
 
-  echo "Uploading ${file} to ${repo} ..."
+  local dest="https://uploads.github.com/repos/${repo}/releases/${PKG_VERSION}/assets?name=$(basename ${file})"
+  echo "Uploading ${file} to ${dest} ..."
 
   local retries=0
   while [ "$retries" -lt "$github_upload_retry_times" ]; do
-    _github-upload-one-internal "${repo}" "${file}" && return 0
+    _github-upload-one-internal "${file}" "${dest}" && return 0
     retries="$((retries + 1))"
     sleep "$github_upload_retry_interval"
   done
 
-  echo >&2 "Failed to upload ${file} to ${repo}"
+  echo >&2 "Failed to upload ${file} to ${dest}"
   return 1
 }
 
 _github-upload-one-internal() {
-  local repo="$1"
-  local file="$2"
+  local src="$1"
+  local dest="$2"
 
-  curl -L \
+  local result
+  result=$(curl -L \
     -X POST \
     -H "Accept: application/vnd.github+json" \
     -H "Authorization: Bearer ${GITHUB_TOKEN}" \
     -H "X-GitHub-Api-Version: 2022-11-28" \
     -H "Content-Type: application/octet-stream" \
-    "https://uploads.github.com/repos/${repo}/releases/"${PKG_VERSION}"/assets?name=$(basename ${file})" \
-    --data-binary "@${file}"
+    "$dest" \
+    --data-binary "@${src}")
+  if [ $? -ne 0 ]; then
+    echo "$result"
+    return 1
+  fi
+
+  grep -q 'Not Found' <<<"${result}"
+  if [ $? -eq 0 ]; then
+    echo "$result"
+    return 1
+  fi
+
+  return 0
 }
