feat(github-action): Add a github composite action

diff --git a/lib/bash/podman b/lib/bash/podman
--- a/lib/bash/podman
+++ b/lib/bash/podman
@@ -7,3 +7,23 @@ podman-run() {
         -w $(pwd) \
         "$@"
 }
+
+podman-setup() {
+    # debian os family
+    which apt-get
+    if [ $$? -eq 0 ]; then
+        sudo apt-get update && sudo apt-get install -y podman
+        return $?
+    fi
+
+    # archlinux
+    which pacman
+    if [ $$? -eq 0 ]; then
+        sudo pacman -Sy podman
+        return $?
+    fi
+
+    echo >&2 "Error: unsupported os family"
+    cat /etc/os-release >&2
+    return 1
+}
